'use strict';

/**
 * Zero-dependency git hook setup.
 *
 * Called automatically by npm's `prepare` lifecycle script after `npm install`.
 * Creates .git/hooks/pre-commit which runs the full test suite before
 * allowing a commit to proceed.
 *
 * If tests fail, the commit is aborted — preventing broken code from
 * entering the repository.
 */

const fs = require('fs');
const path = require('path');

const hookPath = path.resolve(__dirname, '..', '.git', 'hooks', 'pre-commit');

const hookContent = `#!/bin/sh
# Auto-generated by tools/setup-hooks.js (npm prepare)
# Runs the full test suite before every commit
# To bypass temporarily: git commit --no-verify

echo "▶ Running test suite (847 tests)..."

cd "$(git rev-parse --show-toplevel)"

# Run tests — abort commit if any fail
output=$(npm test 2>&1)
exit_code=$?

# Show last 15 lines of output for context
echo "$output" | tail -15

if [ $exit_code -ne 0 ]; then
    echo ""
    echo "✗ TESTS FAILED — commit aborted."
    echo "  Fix the failing tests or use 'git commit --no-verify' to bypass (not recommended)."
    exit 1
fi

echo "✓ All tests passed — proceeding with commit."
`;

try {
    // Ensure .git/hooks directory exists
    const hooksDir = path.dirname(hookPath);
    if (!fs.existsSync(hooksDir)) {
        fs.mkdirSync(hooksDir, { recursive: true });
    }

    fs.writeFileSync(hookPath, hookContent);
    fs.chmodSync(hookPath, 0o755); // Make executable
    console.log('✓ Pre-commit hook installed (.git/hooks/pre-commit)');
    console.log('  Runs npm test before every commit');
    console.log('  Bypass with: git commit --no-verify');
} catch (err) {
    console.warn('⚠ Could not install pre-commit hook:', err.message);
    console.warn('  Tests will still run via npm test and GitHub Actions CI.');
}
